.TH "FL-CREDENTIAL-CTL" "1" "26 March 2009" "Debian Project" "Debian manual"
.SH "NAME"
fl\-credential\-ctl \- XML\-RPC credential server for funkload
.SH "SYNOPSIS"
.B fl\-credential\-ctl
.B [ options ]
.B config_file
.B [ start | startd | stop | restart | status | test ]
.SH "DESCRIPTION"
fl\-credential\-ctl controls the XML\-RPC based credential server for Funkload. This server is meant to be used in order to write benchs that require authentication.
.PP
A configuration file needs to be setup in order to use this server. Please refer to demo/cmf/credential.conf for an example.
.SH "OPTIONS"
.TP
.B \-\-version
Show program's version number and exit
.TP
.B \-\-help, \-h
Show a help message and exit
.TP
.B \-\-quiet, \-q
Verbose output
.SH "SEE ALSO"
.BR fl\-build\-report (1),
.BR fl\-install\-demo (1),
.BR fl\-monitor\-ctl (1),
.BR fl\-record (1),
.BR fl\-run\-bench (1),
.BR fl\-run\-test (1).
.SH "AUTHOR"
Funkload was written by Benoit Delbosc.
.PP
This manual page was written by Jose Parrella <bureado@debian.org>,
for the Debian project (but may be used by others).
