.TH "FL-INSTALL-DEMO" "1" "26 March 2009" "Debian Project" "Debian manual"
.SH "NAME"
fl\-install\-demo \- installs funkload demonstration files
.SH "SYNOPSIS"
.B fl\-install\-demo
.SH "DESCRIPTION"
fl\-install\-demo installs the funkload demonstration files in ./funkload\-demo
.SH "SEE ALSO"
.BR fl\-build\-report (1),
.BR fl\-credential\-ctl (1),
.BR fl\-monitor\-ctl (1),
.BR fl\-record (1),
.BR fl\-run\-bench (1),
.BR fl\-run\-test (1).
.SH "AUTHOR"
Funkload was written by Benoit Delbosc.
.PP 
This manual page was written by Jose Parrella <bureado@debian.org>,
for the Debian project (but may be used by others).
