.TH "FL-RECORD" "1" "26 March 2009" "Debian Project" "Debian manual"
.SH "NAME"
fl\-record \- records a live funkload test using TCPWatch
.SH "SYNOPSIS"
.B fl\-record
.B [ options ]
.B test_case
.SH "DESCRIPTION"
fl\-record uses TCPWatch to setup a proxy server which is then used by a browser and records activities. It generates a Funkload script or a unit test if a name is passed to the script.
.SH "OPTIONS"
.TP 
.B \-\-version
Show program's version number and exit
.TP 
.B \-\-help, \-h
Show a help message and exit
.TP 
.B \-\-verbose, \-v
Verbose output
.TP 
.B \-\-port=PORT, \-p PORT
TCP port where the proxy listens (Defaults to 8090)
.TP 
.B \-\-tcp\-watch\-input=TCPWATCH_PATH, \-i TCPWATCH_PATH
Path to an existing TCPWatch capture
.TP
.B --loop=LOOP, -l LOOP
Loop mode
.SH "SEE ALSO"
.BR fl\-build\-report (1),
.BR fl\-credential\-ctl (1),
.BR fl\-install\-demo (1),
.BR fl\-monitor\-ctl (1),
.BR fl\-run\-bench (1),
.BR fl\-run\-test (1).
.SH "AUTHOR"
Funkload was written by Benoit Delbosc.
.PP 
This manual page was written by Jose Parrella <bureado@debian.org>,
for the Debian project (but may be used by others).
