#!/bin/bash
# manage the monitor server
# $Id: fl-monitor-ctl 24514 2005-08-25 15:54:36Z bdelbosc $

if [ -n "$FL_HOME" ]; then
    FL_SRC=$FL_HOME/funkload
    echo "### Using src in $FL_SRC"
else
    # XXX should find this dynamicly
    FL_SRC=/usr/lib/python2.3/site-packages/funkload
fi

start() {
    echo "### monitorctl: Starting monitor server."
    (python $FL_SRC/monitord.py $conf_path  >> $LOGFILE 2>&1 || echo "### monitorctl: ERROR server not started use monitorctl CONF_PATH log for more info") &

}


startd() {
    echo "### monitorctl: Starting monitor server in debug mode:"
    python $FL_SRC/monitord.py $conf_path
}


stop() {
    echo "### monitorctl: Stopping monitor server:"
    python $FL_SRC/monitorctl.py $conf_path stop
}

test_server() {
    echo "### monitorctl: Testing monitor server:"
    python $FL_SRC/monitorctl.py $conf_path test
}

status() {
    echo "### monitorctl: Checking monitor server status:"
    python $FL_SRC/monitorctl.py $conf_path status
}

reload() {
    echo "### monitorctl: Checking monitor server reload:"
    python $FL_SRC/monitorctl.py $conf_path reload
}

record() {
    echo "### monitorctl: Recording key $1"
    python $FL_SRC/monitorctl.py $conf_path monitor_start $1
}

get_result() {
    echo "### monitorctl: Result for key $1"
    python $FL_SRC/monitorctl.py $conf_path monitor_get $1
}

record_stop() {
    echo "### monitorctl: Stop recording key $1"
    python $FL_SRC/monitorctl.py $conf_path monitor_stop $1
}



usage() {
    echo "Usage: $0 CONF_PATH {start|startd|stop|restart|status|log|record [KEY]|stop_record [KEY]|get [KEY]}"
}

LOGFILE=monitord.log

if [ ! -f $1 ]; then
    usage
    exit 1
fi

conf_path=$1
shift

case "$1" in
    start)
        start;;
    startd)
        startd;;
    stop)
        stop;;
    status)
        status;;
    reload|force-reload)
        reload
        status;;
    get|result|stat)
        get_result $2;;
    record|monitor_start)
        record $2;;
    stop_record|monitor_stop|record_stop)
        record_stop $2;;
    restart)
        stop
        sleep 1
        start
        status
        ;;
    test|check)
        test_server
        ;;
    log)
        echo "### monitorctl: tail -f $LOGFILE"""
        tail -f $LOGFILE
        ;;
    *)
        usage
        exit 1
        ;;
esac

